/* Croatian dictionary, part 5: 24 Sep 2026 alignment (Marko, Locastic).
   Verbatim from the brief: „Svaki potrošeni euro nosi 1 bod", „100 bodova = 1 euro popusta",
   „Završetkom narudžbe zarađujete … bodova", „Neki artikli ne nose bodove ili nose ograničen broj bodova.",
   „Kupnja plaćena bodovima ne donosi nove bodove.", „Bodovi vrijede 24 mjeseca.",
   „Zaradili ste nove bodove. Pogledajte stanje u aplikaciji.", „Imate … bodova spremnih za korištenje",
   „Bodovi i zamjene", „Sustav", DPD na adresu, DPD paketomat, GLS paketomat, the WSPay group label.
   Everything else in this file is a neutral placeholder: COPY REVIEW (Locastic writes final microcopy).
   {P} is the programme name from e24-brand.js. */
(function(){
const pl = s => { const n = parseInt(String(s).replace(/\./g,''), 10); const a = n % 10, b = n % 100;
  return a === 1 && b !== 11 ? 'bod' : a >= 2 && a <= 4 && (b < 12 || b > 14) ? 'boda' : 'bodova'; };
window.E24_HR = Object.assign(window.E24_HR || {}, {
/* G-03 pair */
"Every euro spent earns 1 point":"Svaki potrošeni euro nosi 1 bod",
"100 points = 1 euro off":"100 bodova = 1 euro popusta",
"Every euro spent earns 1 point. 100 points = 1 euro off.":"Svaki potrošeni euro nosi 1 bod. 100 bodova = 1 euro popusta.",
"No points yet. Every euro spent earns 1 point.":"Još nemate bodova. Svaki potrošeni euro nosi 1 bod.",
"50 welcome points. Every euro spent earns 1 point.":"50 bodova dobrodošlice. Svaki potrošeni euro nosi 1 bod.",
"Every euro spent earns 1 point. Points are earned in all 21 pharmacies, on eljekarna24.hr, at Centar zdravih rješenja and in this app. Show your QR card at the register so an in-store purchase counts.":"Svaki potrošeni euro nosi 1 bod. Bodovi se skupljaju u svih 21 ljekarni, na eljekarna24.hr, u Centru zdravih rješenja i u ovoj aplikaciji. Pokažite QR karticu na blagajni kako bi se kupnja u ljekarni zabilježila.",
"100 points = 1 euro off. You can use them from 100 points upward, up to the value of your order.":"100 bodova = 1 euro popusta. Možete ih iskoristiti od 100 bodova naviše, do iznosa narudžbe.",
"Every euro spent earns 1 point,\nin every channel":"Svaki potrošeni euro nosi 1 bod,\nna svakom kanalu",
"Earn in the app, on both webshops and at the register. 100 points = 1 euro off.":"Skupljajte u aplikaciji, u obje web trgovine i na blagajni. 100 bodova = 1 euro popusta.",
/* G-05, C-05, C-06 */
"A purchase paid for with points does not earn new points.":"Kupnja plaćena bodovima ne donosi nove bodove.",
"No. A purchase paid for with points does not earn new points.":"Ne. Kupnja plaćena bodovima ne donosi nove bodove.",
"Some items earn no points or a limited number of points.":"Neki artikli ne nose bodove ili nose ograničen broj bodova.",
"Points are temporarily unavailable":"Bodovi trenutačno nisu dostupni",
"Your order is not affected. Points for it are added once the service is back.":"To ne utječe na narudžbu. Bodovi za nju dodaju se kada usluga ponovno proradi.",
"Points cannot be used right now because the service is temporarily unavailable. You can still place the order.":"Bodove trenutačno nije moguće iskoristiti jer usluga privremeno nije dostupna. Narudžbu i dalje možete poslati.",
"Subtotal":"Međuzbroj",
/* G-06 */
"Points are valid for 24 months.":"Bodovi vrijede 24 mjeseca.",
"How long are points valid?":"Koliko dugo vrijede bodovi?",
/* G-07 push */
"New points":"Novi bodovi",
"You have earned new points. Check your balance in the app.":"Zaradili ste nove bodove. Pogledajte stanje u aplikaciji.",
"Short maintenance":"Kratko održavanje",
"Points earned during maintenance are added once it finishes.":"Bodovi zarađeni tijekom održavanja dodaju se kada ono završi.",
"Pharmacist advice":"Savjet ljekarnika",
"Advice for the winter months. See the offers in the app.":"Savjeti za zimske mjesece. Pogledajte ponudu u aplikaciji.",
/* N-01 tabs, F-01 wishlist */
"Home":"Početna","Shop":"Trgovina","Wishlist":"Lista želja","Profile":"Profil",
"Saved to your wishlist":"Spremljeno na listu želja",
"Save to wishlist":"Spremi na listu želja","Remove from wishlist":"Ukloni s liste želja",
"Your wishlist is empty":"Vaša lista želja je prazna",
"Tap the heart on any product to save it here.":"Dodirnite srce na proizvodu da ga spremite ovdje.",
"Go to the shop":"Idi u trgovinu",
/* G-12 labels, C-01..C-04 */
"Gift":"Poklon","Recommended":"Preporuka",
"In stock":"Na zalihi","Out of stock":"Nema na zalihi",
"Product notice":"Napomena o proizvodu","Micronutrients":"Mikronutrijenti","Per tablet":"Po tableti","Product details":"Detalji proizvoda",
"Why take it":"Zašto ga uzimati","How to take it":"Kako ga uzimati","Ingredients":"Sastojci","Warnings":"Upozorenja","Storage":"Čuvanje",
"Vitamin C":"Vitamin C","Vitamin D":"Vitamin D","Zinc":"Cink",
"Food supplement. Not a substitute for a varied and balanced diet and a healthy lifestyle. Keep out of the reach of small children.":"Dodatak prehrani. Nije zamjena za raznoliku i uravnoteženu prehranu i zdrav način života. Čuvati izvan dohvata male djece.",
"Biocidal product. Use safely. Always read the label and the product information before use.":"Biocidni proizvod. Koristite ga sigurno. Prije uporabe uvijek pročitajte oznaku i podatke o proizvodu.",
"Medical device. Read the instructions for use before first use.":"Medicinski proizvod. Prije prve uporabe pročitajte upute za uporabu.",
"Vitamins C and D and zinc contribute to the normal function of the immune system. Zinc is also needed for a large number of enzymes to work properly and helps protect cells from oxidative stress. Intended as everyday immune support, particularly through the colder months.":"Vitamini C i D te cink pridonose normalnoj funkciji imunološkog sustava. Cink je potreban i za pravilan rad velikog broja enzima te pomaže u zaštiti stanica od oksidativnog stresa. Namijenjeno svakodnevnoj potpori imunitetu, osobito u hladnijim mjesecima.",
"Adults and children over 14: one effervescent tablet a day. Dissolve the tablet in a glass of water (200 ml) and drink. Do not exceed the recommended daily dose.":"Odrasli i djeca starija od 14 godina: jedna šumeća tableta dnevno. Tabletu otopite u čaši vode (200 ml) i popijte. Ne prekoračujte preporučenu dnevnu dozu.",
"L-ascorbic acid; acidity regulator: sodium carbonate; acid: citric acid; bulking agent: isomalt; acid: malic acid; colour: beta-carotene; orange flavouring; zinc citrate; sweeteners: acesulfame K, sucralose; sodium chloride; cholecalciferol.":"L-askorbinska kiselina; regulator kiselosti: natrijev karbonat; kiselina: limunska kiselina; tvar za povećanje volumena: izomalt; kiselina: jabučna kiselina; bojilo: beta-karoten; aroma naranče; cinkov citrat; sladila: acesulfam K, sukraloza; natrijev klorid; kolekalciferol.",
"Not recommended for people with haemochromatosis, hypercalcaemia or kidney disease, or for women who are pregnant or breastfeeding. Contains sweeteners. If you take other vitamin D or zinc preparations, check your total daily intake with your pharmacist.":"Ne preporučuje se osobama s hemokromatozom, hiperkalcijemijom ili bolešću bubrega te trudnicama i dojiljama. Sadrži sladila. Ako uzimate druge pripravke s vitaminom D ili cinkom, provjerite ukupan dnevni unos s ljekarnikom.",
"Keep in the original tube in a dry place below 25 °C, out of the reach of small children. A food supplement is not a substitute for a balanced, varied diet and a healthy lifestyle.":"Čuvati u originalnoj tubi na suhom mjestu pri temperaturi do 25 °C, izvan dohvata male djece. Dodatak prehrani nije zamjena za uravnoteženu i raznoliku prehranu i zdrav način života.",
"Two additions this month.":"Dva nova proizvoda ovog mjeseca.",
"Recent additions for skin, hair and nails.":"Novo za kožu, kosu i nokte.",
/* C-07..C-13 checkout */
"DPD to my address":"DPD na adresu","DPD parcel locker":"DPD paketomat","GLS parcel locker":"GLS paketomat",
"Parcel lockers and pick-up points belong to DPD and GLS and are located in other shops, never in Švaljek pharmacies.":"Paketomati i paketne točke pripadaju DPD-u i GLS-u i nalaze se u drugim trgovinama, nikada u ljekarnama Švaljek.",
"Google Pay, KEKS Pay, Aircash, PayCek, card payment":"Google Pay, KEKS Pay, Aircash, PayCek, kartično plaćanje",
"On the secure WSPay page":"Na sigurnoj WSPay stranici",
"Card":"Kartica","Card payment":"Kartično plaćanje","Bank transfer":"Bankovni prijenos",
"Card details entered here in the app":"Podaci o kartici unose se ovdje u aplikaciji",
"Card number":"Broj kartice","Expires":"Vrijedi do","CVC":"CVC",
"Card details go straight to Stripe over an encrypted connection. Your bank may ask you to confirm the payment.":"Podaci o kartici šalju se izravno Stripeu putem šifrirane veze. Banka od vas može zatražiti potvrdu plaćanja.",
"You choose how to pay on the secure WSPay page, then return here. A card can be saved on the WSPay page for next time.":"Način plaćanja birate na sigurnoj WSPay stranici, a zatim se vraćate ovdje. Karticu za sljedeći put možete spremiti na WSPay stranici.",
"You get the payee, IBAN, model, reference and amount on the confirmation screen and in the email. {P} points cannot be used with bank transfer.":"Primatelja, IBAN, model, poziv na broj i iznos dobit ćete na ekranu potvrde i u e-pošti. {P} bodovi ne mogu se koristiti uz bankovni prijenos.",
"You get the payee, IBAN, model, reference and amount on the confirmation screen and in the email. {P} points cannot be used with bank transfer. The discount on your order has been removed.":"Primatelja, IBAN, model, poziv na broj i iznos dobit ćete na ekranu potvrde i u e-pošti. {P} bodovi ne mogu se koristiti uz bankovni prijenos. Popust na narudžbi je uklonjen.",
"Not available with bank transfer, because the payment is settled later. Switch to card or WSPay to use your points.":"Nije dostupno uz bankovni prijenos jer se plaćanje podmiruje naknadno. Odaberite karticu ili WSPay kako biste iskoristili bodove.",
"A payment settled later cannot be combined with points, so the discount was removed when you changed the payment method. Switch back to card or WSPay to use the points again.":"Plaćanje koje se podmiruje naknadno ne može se kombinirati s bodovima pa je popust uklonjen kada ste promijenili način plaćanja. Odaberite ponovno karticu ili WSPay kako biste iskoristili bodove.",
"Your points were taken off this order":"Bodovi su uklonjeni s ove narudžbe",
"Your points cover the whole order. There is nothing left to pay.":"Bodovi pokrivaju cijelu narudžbu. Nema ništa za platiti.",
"{P} points are not a code. Use the switch above.":"{P} bodovi nisu kod. Koristite prekidač iznad.",
"{P} points":"{P} bodovi",
"Delivery prices are calculated from this address. The name on your {P} card comes from it too.":"Cijene dostave računaju se prema ovoj adresi. S nje dolazi i ime na vašoj {P} kartici.",
"Edit":"Uredi","Edit address":"Uredi adresu","Save changes":"Spremi promjene",
"It is processed as soon as your transfer arrives. The details are below and in the confirmation email.":"Obrađuje se čim uplata stigne. Podaci su u nastavku i u e-pošti s potvrdom.",
"Points are credited when the payment is confirmed.":"Bodovi se dodjeljuju kada je plaćanje potvrđeno.",
"Points are credited once the order is completed.":"Bodovi se dodjeljuju kada je narudžba dovršena.",
"Points were credited when the order was completed.":"Bodovi su dodijeljeni kada je narudžba dovršena.",
"Points after payment":"Bodovi nakon plaćanja",
"View this order":"Pogledaj narudžbu",
"WSPay":"WSPay",
"Secure WSPay page, shown inside {P}. You can cancel at any time.":"Sigurna WSPay stranica, prikazana unutar aplikacije {P}. Plaćanje možete otkazati u bilo kojem trenutku.",
"Pay":"Plati",
"Waiting for payment confirmation":"Čekamo potvrdu plaćanja",
"Waiting for confirmation":"Čekamo potvrdu",
"Payment confirmed":"Plaćanje potvrđeno",
"Cancel and choose another method":"Odustani i odaberi drugi način",
"Prototype: show a declined payment":"Prototip: prikaži odbijeno plaćanje",
"Payment":"Plaćanje",
"The payment did not go through":"Plaćanje nije uspjelo",
"The payment was declined. Nothing was charged and your order is unchanged.":"Plaćanje je odbijeno. Ništa nije naplaćeno i narudžba je nepromijenjena.",
"Try again":"Pokušaj ponovno","Choose another method":"Odaberi drugi način",
"This screen is your bank’s, shown inside the app. The app never sees the code.":"Ovaj ekran pripada vašoj banci i prikazan je unutar aplikacije. Aplikacija nikada ne vidi kod.",
"Awaiting payment":"Čeka uplatu","Received":"Zaprimljena",
/* C-14 orders */
"In-store purchases are not orders. They appear in your points history.":"Kupnje u ljekarni nisu narudžbe. Prikazuju se u povijesti bodova.",
"Orders from the app and from eljekarna24.hr appear here.":"Ovdje se prikazuju narudžbe iz aplikacije i s eljekarna24.hr.",
"No orders here":"Ovdje nema narudžbi",
"Tracking number":"Broj za praćenje",
"App":"Aplikacija","eljekarna24.hr":"eljekarna24.hr",
/* D-01..D-04 */
"Your points":"Vaši bodovi","your points":"vaši bodovi",
"Show this code at the register in any of the 21 pharmacies. Points are added to your balance within a few minutes.":"Pokažite ovaj kod na blagajni u bilo kojoj od 21 ljekarne. Bodovi se dodaju na stanje u roku od nekoliko minuta.",
"The pass in your wallet carries your QR code and name. Check your balance here in the app.":"Kartica u novčaniku sadrži vaš QR kod i ime. Stanje bodova provjerite ovdje u aplikaciji.",
"Works offline. The code is stored on this device.":"Radi bez interneta. Kod je spremljen na ovom uređaju.",
"100+ points? Tell the cashier you would like to use them. No step in the app is needed.":"Imate 100 ili više bodova? Recite blagajniku da ih želite iskoristiti. U aplikaciji ne trebate ništa napraviti.",
"Points history":"Povijest bodova","Recent activity":"Nedavna aktivnost",
"How {P} works":"Kako funkcionira {P}","How it works":"Kako funkcionira",
"Points count in all 21 pharmacies, on eljekarna24.hr, at Centar zdravih rješenja and in this app.":"Bodovi se skupljaju u svih 21 ljekarni, na eljekarna24.hr, u Centru zdravih rješenja i u ovoj aplikaciji.",
"In the app: one switch at checkout, from 100 points upward.":"U aplikaciji: jedan prekidač pri plaćanju, od 100 bodova naviše.",
"In store: show your card and tell the cashier you would like to use your points.":"U ljekarni: pokažite karticu i recite blagajniku da želite iskoristiti bodove.",
"Store":"Poslovnica","e24 web":"e24 web","Centar zdravih rješenja web":"Centar zdravih rješenja web",
"Birthday bonus":"Rođendanski bonus","Welcome bonus":"Bonus dobrodošlice",
"Channel":"Kanal","Saved":"Ušteđeno","Date":"Datum","Points":"Bodovi","Processing":"U obradi",
"This purchase is still being processed. Points from in-store purchases appear within a few minutes.":"Ova se kupnja još obrađuje. Bodovi za kupnje u ljekarni pojavljuju se u roku od nekoliko minuta.",
"Bonus points are added to your balance like any other points.":"Bonus bodovi dodaju se na stanje kao i svi ostali bodovi.",
"A refund removes the points the purchase earned.":"Povrat uklanja bodove koje je kupnja donijela.",
"Your balance is −15 points":"Vaše stanje je −15 bodova",
"A refund exceeded your available balance. Future purchases bring it back up to zero, then beyond.":"Povrat je premašio raspoloživo stanje. Buduće kupnje vratit će ga na nulu, a zatim i više.",
"Points from in-store purchases appear within a few minutes. Refunds are shown as their own rows and remove the points the purchase earned.":"Bodovi za kupnje u ljekarni pojavljuju se u roku od nekoliko minuta. Povrati se prikazuju kao zasebni retci i uklanjaju bodove koje je kupnja donijela.",
"Your card is waiting on your email":"Kartica čeka potvrdu e-pošte",
"The QR code works once you open the confirmation link we sent. Until then, points cannot be added at the register.":"QR kod radi nakon što otvorite poveznicu za potvrdu koju smo poslali. Do tada se bodovi ne mogu dodati na blagajni.",
"Enlarge code for scanning":"Povećaj kod za skeniranje","Exit scanning mode":"Izađi iz načina skeniranja",
"Your name appears here after your first delivery address":"Vaše ime pojavit će se ovdje nakon prve adrese za dostavu",
"Add to Apple / Google Wallet":"Dodaj u Apple / Google Wallet","Added to your wallet":"Dodano u novčanik",
"The cashier's discount is applied. Your balance here updates within a few minutes.":"Popust na blagajni je primijenjen. Stanje se ovdje ažurira u roku od nekoliko minuta.",
"A redemption at the till is still settling":"Iskorištavanje bodova na blagajni još se obrađuje",
"last known balance":"posljednje poznato stanje","balance refreshing":"stanje se osvježava",
"+41 points from a recent purchase is still processing.":"+41 bod iz nedavne kupnje još je u obradi.",
"Your QR code":"Vaš QR kod",
/* E-01..E-06 */
"Sign out and delete account":"Odjava i brisanje računa",
"Help and legal":"Pomoć i pravne informacije","Programme rules":"Pravila programa",
"Programme rules, supplied by the client. Editable in BigCommerce.":"Pravila programa dostavlja klijent. Uređuju se u BigCommerceu.",
"Legal text, supplied by the client. Editable in BigCommerce.":"Pravni tekst dostavlja klijent. Uređuje se u BigCommerceu.",
"Sign out of {P}?":"Odjaviti se iz aplikacije {P}?",
"{P} · Ljekarne Švaljek · Version 1.0":"{P} · Ljekarne Švaljek · Verzija 1.0",
"Taken from your first delivery address. It also appears on your {P} card.":"Preuzeto s prve adrese za dostavu. Prikazuje se i na vašoj {P} kartici.",
"Date of birth":"Datum rođenja","Optional. Used for your birthday bonus.":"Neobavezno. Koristi se za rođendanski bonus.",
"Changing your email sends a confirmation link to the new address. The change applies once you open it. Your points balance is not affected.":"Promjenom e-pošte na novu adresu šaljemo poveznicu za potvrdu. Promjena vrijedi nakon što je otvorite. Stanje bodova ostaje isto.",
"Email about my orders":"E-pošta o mojim narudžbama",
"Confirmations and delivery updates. Cannot be turned off for orders in progress.":"Potvrde i obavijesti o dostavi. Ne može se isključiti dok je narudžba u tijeku.",
"Marketing by email":"Marketing putem e-pošte",
"Offers and news by email. Push notifications are set separately in Notifications.":"Ponude i novosti e-poštom. Push obavijesti postavljaju se zasebno u Obavijestima.",
"Marketing emails are on":"Marketinška e-pošta je uključena","Marketing emails are off":"Marketinška e-pošta je isključena",
"Withdrawing a consent takes effect immediately. It does not affect your {P} membership or your points.":"Povlačenje privole vrijedi odmah. Ne utječe na vaše {P} članstvo ni na bodove.",
"How do I earn points?":"Kako skupljam bodove?","What are my points worth?":"Koliko vrijede moji bodovi?","How do I spend them?":"Kako ih mogu iskoristiti?",
"In the app, turn on the switch at the review step. In a pharmacy, tell the cashier you would like to use your points.":"U aplikaciji uključite prekidač u koraku pregleda narudžbe. U ljekarni recite blagajniku da želite iskoristiti bodove.",
"Why has my balance not gone up yet?":"Zašto mi se stanje još nije povećalo?",
"Points from in-store purchases appear within a few minutes. Points from an online order are credited once the order is completed.":"Bodovi za kupnje u ljekarni pojavljuju se u roku od nekoliko minuta. Bodovi za online narudžbu dodjeljuju se kada je narudžba dovršena.",
"Does a purchase paid with points earn points?":"Donosi li kupnja plaćena bodovima nove bodove?",
"Which prescriptions can I order?":"Koje lijekove na recept mogu naručiti?",
"Prescription medicines and co-payments are settled in the pharmacy and cannot be paid for in the app.":"Lijekovi na recept i participacije podmiruju se u ljekarni i ne mogu se platiti u aplikaciji.",
"How do I return something?":"Kako mogu vratiti proizvod?",
"Returns follow the terms of use. Points earned on a returned item are removed when the refund is processed.":"Povrat se provodi prema uvjetima korištenja. Bodovi zarađeni na vraćenom proizvodu uklanjaju se kada se povrat obradi.",
"Where do you deliver?":"Kamo dostavljate?",
"Anywhere in Croatia, by courier to your address or to a parcel locker.":"Bilo gdje u Hrvatskoj, kurirskom službom na adresu ili u paketomat.",
"Password updated. You stay signed in on this device.":"Lozinka je promijenjena. Na ovom uređaju ostajete prijavljeni.",
"Biometrics":"Biometrija","Security & sign-in":"Sigurnost i prijava",
"My data":"Moji podaci","Sign out":"Odjava",
"Request a copy of my data":"Zatraži kopiju mojih podataka",
"Your request for a copy of your data has been received and will be processed. The copy is sent to iva.jurasin@primjer.hr.":"Vaš zahtjev za kopiju podataka je zaprimljen i bit će obrađen. Kopija se šalje na iva.jurasin@primjer.hr.",
"Your request to delete the account has been received and will be processed. We will confirm by email to iva.jurasin@primjer.hr.":"Vaš zahtjev za brisanje računa je zaprimljen i bit će obrađen. Potvrdu šaljemo e-poštom na iva.jurasin@primjer.hr.",
"Delete account":"Brisanje računa","Request account deletion":"Zatraži brisanje računa",
"Deleting removes your profile and addresses and closes your {P} membership. Unspent points are lost and cannot be restored.":"Brisanjem se uklanjaju profil i adrese te se zatvara vaše {P} članstvo. Neiskorišteni bodovi se gube i ne mogu se vratiti.",
"Delete your account?":"Izbrisati račun?",
"The request cannot be undone once it is processed. Spend your points before you go.":"Nakon obrade zahtjev se ne može poništiti. Iskoristite bodove prije odlaska.",
"Profile and addresses are deleted.":"Profil i adrese se brišu.",
"{P} membership closes and unspent points are lost.":"{P} članstvo se zatvara, a neiskorišteni bodovi se gube.",
"Send deletion request":"Pošalji zahtjev za brisanje","Keep my account":"Zadrži račun",
"Points and redemptions":"Bodovi i zamjene","Offers and news":"Ponude i novosti","System":"Sustav",
"Push is the only place a points confirmation appears. You can always check your balance in the points history.":"Push obavijest jedino je mjesto na kojem se pojavljuje potvrda o bodovima. Stanje uvijek možete provjeriti u povijesti bodova.",
"Push is switched off for {P}":"Push obavijesti za {P} su isključene",
"Points confirmations arrive by push only. You can always check your balance in the points history. Turn notifications back on for {P} in your phone settings.":"Potvrde o bodovima stižu samo push obaviješću. Stanje uvijek možete provjeriti u povijesti bodova. Ponovno uključite obavijesti za {P} u postavkama telefona.",
"Notifications are delivered by the operating system. They cannot arrive if push is switched off for the app in your phone settings.":"Obavijesti isporučuje operativni sustav. Ne mogu stići ako su push obavijesti za aplikaciju isključene u postavkama telefona.",
"Push is the only place points are announced. Choose what you want to hear about.":"Bodovi se najavljuju samo push obaviješću. Odaberite o čemu želite primati obavijesti.",
"Service notices about the app: maintenance, outages and changes to the programme.":"Servisne obavijesti o aplikaciji: održavanje, prekidi i promjene programa.",
"System notifications are on":"Obavijesti sustava su uključene","System notifications are off":"Obavijesti sustava su isključene",
"Offers and news notifications are on":"Obavijesti o ponudama i novostima su uključene","Offers and news notifications are off":"Obavijesti o ponudama i novostima su isključene",
/* A-01..A-03, S-01, S-02 */
"The pharmacy range, ordered from here":"Ljekarnička ponuda, naručena odavde",
"Browse the full e24 range and choose delivery to your door or to a parcel locker.":"Pregledajte cijelu e24 ponudu i odaberite dostavu na adresu ili u paketomat.",
"Your card, on your phone":"Vaša kartica, na vašem telefonu",
"Show the QR code at the register and your points are added within a few minutes.":"Pokažite QR kod na blagajni i bodovi se dodaju u roku od nekoliko minuta.",
"Log in to see your points, your orders and your saved addresses.":"Prijavite se da vidite bodove, narudžbe i spremljene adrese.",
"New to {P}?":"Prvi put u aplikaciji {P}?",
"Your {P} membership starts with the account. Points from the register are added to the same balance.":"Vaše {P} članstvo počinje s računom. Bodovi s blagajne dodaju se na isto stanje.",
"Date of birth (optional)":"Datum rođenja (neobavezno)",
"Add it to receive 50 bonus points on your birthday.":"Unesite ga i za rođendan dobivate 50 bonus bodova.",
"and the {P} programme rules.":"i pravila programa {P}.",
"Send me pharmacist advice and news, by email and push. You can turn this off at any time in":"Šaljite mi savjete ljekarnika i novosti e-poštom i push obavijestima. To možete isključiti u bilo kojem trenutku u",
"Choose a password you have not used before. You stay logged in on this device afterwards.":"Odaberite lozinku koju još niste koristili. Nakon toga ostajete prijavljeni na ovom uređaju.",
"{P} stays on hold until the address is confirmed. No points and no QR card until then.":"{P} miruje dok adresa nije potvrđena. Do tada nema bodova ni QR kartice.",
"{P} is on hold until you open the link we sent to ana.horvat@primjer.hr. Shopping works normally.":"{P} miruje dok ne otvorite poveznicu koju smo poslali na ana.horvat@primjer.hr. Kupnja radi normalno.",
"Welcome to {P}. Your balance starts at":"Dobro došli u {P}. Vaše stanje počinje s",
"placeholder — amount to confirm":"privremeno — iznos treba potvrditi",
"Your QR card is always on your phone.":"QR kartica uvijek vam je na telefonu.",
"Create one in under a minute, or log in. You come straight back to this product.":"Izradite ga za manje od minute ili se prijavite. Vraćate se ravno na ovaj proizvod.",
"Browsing needs no account. The cart, the wishlist, {P} and the profile do.":"Za pregledavanje ne treba račun. Za košaricu, listu želja, {P} i profil treba.",
"We cannot reach {P} right now. Your card still works without a connection. The QR code is stored on this phone.":"Trenutačno ne možemo doći do usluge {P}. Kartica radi i bez veze. QR kod je spremljen na ovom telefonu.",
"{P} is being updated":"{P} se ažurira",
"Ordering is unavailable for a short while. Points earned in a pharmacy during this time are added as soon as the service is back.":"Naručivanje je kratko nedostupno. Bodovi zarađeni u ljekarni u tom razdoblju dodaju se čim usluga ponovno proradi.",
"No connection":"Nema veze","Offline":"Izvan mreže","Open system settings":"Otvori postavke sustava",
"Confirm your email address":"Potvrdite adresu e-pošte",
"Lockers and counter hand-over points in other shops are both in this list — the type is shown on each location.":"Na popisu su paketomati i paketne točke u drugim trgovinama. Vrsta je navedena uz svaku lokaciju.",
"The name on your default address is the name shown on your {P} card.":"Ime na zadanoj adresi prikazuje se na vašoj {P} kartici.",
"The name on this address becomes the name on your {P} card.":"Ime na ovoj adresi postaje ime na vašoj {P} kartici.",
"collection points":"točke preuzimanja","near you":"u blizini",
"Payee":"Primatelj","Model":"Model","Reference":"Poziv na broj","Amount":"Iznos",
"Authentication code":"Kod za autentifikaciju",
"· Store":"· Poslovnica","· App":"· Aplikacija","· e24 web":"· e24 web","· Centar zdravih rješenja web":"· Centar zdravih rješenja web",
"Time left to confirm:":"Preostalo vrijeme za potvrdu:",
"Two fields need attention":"Dva polja treba ispraviti",
"Both are marked below. Nothing else on the form was lost.":"Oba su označena u nastavku. Ništa drugo u obrascu nije izgubljeno."
});
window.E24_HR_RULES = [
  [/^([+\u2212])([\d.]+) pts$/, (m, sg, n) => sg + n + ' ' + pl(n)],
  [/^You have ([\d.]+) points ready to spend\.$/, "Imate $1 bodova spremnih za korištenje"],
  [/^You have ([\d.]+) points\. ([\d.]+) more to your first €1\.$/, "Imate $1 bodova. Još $2 do prvog eura popusta."],
  [/^Complete this order to earn ([\d.]+) points$/, (m, n) => 'Završetkom narudžbe zarađujete ' + n + ' ' + pl(n)],
  [/^Promotion: (.+) · until (.+)$/, "Akcija: $1 · do $2"],
  [/^Promotion: (.+)$/, "Akcija: $1"],
  [/^View order (.+)$/, "Pogledaj narudžbu $1"],
  [/^Order (WP-[\d-]+)$/, "Narudžba $1"],
  [/^Points used on order (.+)$/, "Bodovi iskorišteni na narudžbi $1"],
  [/^Refund on order (.+)$/, "Povrat za narudžbu $1"],
  [/^€([\d.,]+) saved$/, "$1 € ušteđeno"],
  [/^([\d.]+) points to the next euro off\.$/, (m, n) => 'Još ' + n + ' ' + pl(n) + ' do sljedećeg eura popusta.'],
  [/^You have ([\d.]+) points \(€([\d.,]+)\) to use at review\.$/, "Imate $1 bodova ($2 €) za korištenje u pregledu narudžbe."],
  [/^([\d.]+) points used, €([\d.,]+) off\. ([\d.]+) points stay on your balance\.$/, "Iskorišteno $1 bodova, $2 € popusta. Na stanju ostaje $3 bodova."],
  [/^([\d.]+) points used, €([\d.,]+) off\.$/, "Iskorišteno $1 bodova, $2 € popusta."],
  [/^([\d.]+) points, €([\d.,]+) off\.$/, "$1 bodova, $2 € popusta."],
  [/^([\d.]+) points so far\. Points can be used from 100 points upward, ([\d.]+) to go\.$/, "Zasad $1 bodova. Bodovi se mogu iskoristiti od 100 bodova naviše, nedostaje još $2."],
  [/^\+([\d.]+) points$/, (m, n) => '+' + n + ' ' + pl(n)],
  [/^([\d.]+) points used$/, "Iskorišteno $1 bodova"],
  [/^€([\d.,]+) saved on this order\. A purchase paid for with points does not earn new points\.$/, "Na ovoj narudžbi ušteđeno je $1 €. Kupnja plaćena bodovima ne donosi nove bodove."],
  [/^Add (.+) to cart$/, "Dodaj $1 u košaricu"]
].concat(window.E24_HR_RULES || []);
})();
