/* Croatian dictionary, part 1 of 2. Keys are the English source strings. */
window.E24_HR = Object.assign(window.E24_HR || {}, {
"1.247 points":"1.247 bodova",
"100 points = €1. You can redeem from 100 points upward, and there is no upper limit beyond the value of your order.":"100 bodova = 1 €. Bodove možete iskoristiti od 100 bodova nadalje, bez gornje granice osim vrijednosti narudžbe.",
"100+ points? Tell the cashier you'd like to redeem — no step in the app needed.":"Imate 100+ bodova? Recite na kasi da želite iskoristiti bodove — u aplikaciji ništa ne morate raditi.",
"1–2 working days":"1–2 radna dana",
"4-minute window to confirm in the Aircash app":"4 minute za potvrdu u aplikaciji Aircash",
"50 welcome points, and one point for every euro after that.":"50 bodova dobrodošlice, a nakon toga jedan bod za svaki euro.",
"A Croatian mobile number has nine digits after +385.":"Hrvatski broj mobitela ima devet cifara nakon +385.",
"A little more detail helps — at least 20 characters.":"Malo više detalja pomaže — najmanje 20 znakova.",
"A message when an order is ready for pick-up.":"Obavijest kada je narudžba spremna za preuzimanje.",
"A one-time code by SMS to +385 91 234 5678 when signing in on a new device.":"Jednokratni kod SMS-om na +385 91 234 5678 pri prijavi na novom uređaju.",
"A payment slip with these details is also in the confirmation email.":"Uplatnica s ovim podacima nalazi se i u e-mailu s potvrdom.",
"A product":"Proizvod",
"Accept the terms of use to continue":"Prihvatite uvjete korištenja za nastavak",
"Account and security":"Račun i sigurnost",
"Add a card":"Dodaj karticu",
"Add a new address":"Dodaj novu adresu",
"Add all":"Dodaj sve",
"Add item to cart":"Dodaj u košaricu",
"Add the house number — couriers cannot deliver without it.":"Dodajte kućni broj — bez njega dostavljač ne može dostaviti paket.",
"Add to Apple / Google Wallet":"Dodaj u Apple / Google Wallet",
"Add to cart":"Dodaj u košaricu",
"Add to order":"Dodaj u narudžbu",
"Added to your cart":"Dodano u košaricu",
"Added to your wallet":"Dodano u Wallet",
"Address removed.":"Adresa je uklonjena.",
"Address saved.":"Adresa je sačuvana.",
"Address updated.":"Adresa je ažurirana.",
"All in this category":"Sve u ovoj kategoriji",
"All movements":"Sve promjene",
"All products":"Svi proizvodi",
"Already have an account?":"Već imate račun?",
"An order":"Narudžba",
"Anywhere in Croatia, by courier to your address or to a parcel locker.":"Bilo gdje u Hrvatskoj, dostavom na vašu adresu ili u paketomat.",
"At least 8 characters":"Najmanje 8 znakova",
"Authentication required":"Potrebna je autentifikacija",
"Autumn immunity":"Imunitet na jesen",
"Awaiting transfer":"Čeka se uplata",
"Back to home":"Natrag na početnu",
"Back to profile":"Natrag na profil",
"Back to start":"Natrag na početak",
"Bank transfer":"Bankovna uplata",
"Both are marked below. Nothing else on the form was lost.":"Oba su označena ispod. Ostali podaci u obrascu su sačuvani.",
"Browse the full e24 range, check what is in stock near you, and choose delivery to your door or to a parcel locker.":"Pregledajte cijelu e24 ponudu, provjerite što je na zalihi u vašoj blizini i odaberite dostavu na adresu ili u paketomat.",
"Browsing needs no account. A cart, WellPlus points and My card do.":"Za pregledavanje ne treba račun. Za košaricu, WellPlus bodove i Moju karticu treba.",
"Buy again":"Kupi ponovno",
"Buy again:":"Kupi ponovno:",
"Campaigns and pharmacist advice. Follows your marketing consent.":"Akcije i savjeti magistara farmacije. Prema vašoj privoli za marketing.",
"Cancel and choose another method":"Odustani i odaberi drugi način",
"Cancel payment":"Odustani od plaćanja",
"Card number":"Broj kartice",
"Cards are stored by the bank, tokenised. e24 never sees the full number.":"Kartice čuva banka, u tokeniziranom obliku. e24 nikada ne vidi cijeli broj.",
"Cash on delivery":"Plaćanje pri dostavi",
"Change email":"Promijeni e-mail",
"Change location":"Promijeni lokaciju",
"Change password":"Promijeni lozinku",
"Changing your email changes the address order confirmations are sent to. Your points balance is not affected.":"Promjenom e-maila mijenja se adresa na koju šaljemo potvrde narudžbi. Stanje bodova ostaje isto.",
"Check your inbox":"Provjerite svoj e-mail",
"Choose a location to continue.":"Odaberite lokaciju za nastavak.",
"Choose a locker":"Odaberite paketomat",
"Choose a password you have not used on e24 before. You stay logged in on this device afterwards.":"Odaberite lozinku koju do sada niste koristili na e24. Nakon toga ostajete prijavljeni na ovom uređaju.",
"Choose or add a card to continue":"Odaberite ili dodajte karticu za nastavak",
"Clear all":"Očisti sve",
"Code expires in":"Kod istječe za",
"Collagen and skin support for the routine that shows on the outside.":"Kolagen i podrška koži za rutinu koja se vidi.",
"Collect any time within 3 days":"Preuzmite u roku od 3 dana",
"Collect any time within 5 days":"Preuzmite u roku od 5 dana",
"Confirm order":"Potvrdi narudžbu",
"Confirm payment":"Potvrdi plaćanje",
"Confirm your email":"Potvrdite svoj e-mail",
"Confirmed by pharmacy":"Potvrdila ljekarna",
"Contact us":"Kontaktirajte nas",
"Contact us within 14 days. Points earned on a returned item are removed when the refund is processed.":"Kontaktirajte nas u roku od 14 dana. Bodovi ostvareni na vraćenom proizvodu uklanjaju se pri obradi povrata.",
"Continue shopping":"Nastavi kupovinu",
"Continue to payment":"Nastavi na plaćanje",
"Coupon or gift card":"Kupon ili poklon bon",
"Courier to my address":"Dostava na moju adresu",
"Covered by points — nothing to charge":"Pokriveno bodovima — nema ničega za naplatu",
"Create account":"Kreiraj račun",
"Create an account":"Kreirajte račun",
"Create one in under a minute, or log in. You come straight back to this product, and anything you picked stays in the cart.":"Kreirajte ga u manje od minute ili se prijavite. Vraćate se točno na ovaj proizvod, a sve odabrano ostaje u košarici.",
"Create your account":"Kreirajte svoj račun",
"Creating your code…":"Kreiramo vaš kod…",
"Croatia only. We deliver to addresses and parcel lockers anywhere in the country.":"Samo Hrvatska. Dostavljamo na adrese i u paketomate u cijeloj zemlji.",
"Curated for skin, hair and nails":"Odabrano za kožu, kosu i nokte",
"DPD has your parcel. Track it in My orders.":"DPD je preuzeo vaš paket. Prati ga u Mojim narudžbama.",
"DPD parcel locker":"DPD paketomat",
"DPD to my address":"DPD na moju adresu",
"DPD · collection code sent by SMS on arrival":"DPD · kod za preuzimanje dolazi SMS-om",
"DPD · tracking assigned when it ships":"DPD · broj za praćenje dodjeljuje se pri otpremi",
"Delete account":"Zatvori račun",
"Delete my account":"Zatvori moj račun",
"Deliver to":"Dostava na",
"Delivery addresses":"Adrese za dostavu",
"Delivery is €4,30 for every option.":"Dostava je 4,30 € za svaku opciju.",
"Delivery prices are calculated from this address. Your name on the WellPlus card comes from it too.":"Cijena dostave računa se za ovu adresu. S nje dolazi i ime na WellPlus kartici.",
"Disinfection, wipes and gloves to keep beside the plasters and the thermometer.":"Dezinfekcija, maramice i rukavice uz flastere i toplomjer.",
"Download invoice":"Preuzmi račun",
"Download my data":"Preuzmi moje podatke",
"Earn on the app, both webshops and at the register. Points never expire, and 100 points are worth €1 off your next order.":"Zarađujte u aplikaciji, na oba webshopa i na kasi. Bodovi ne istječu, a 100 bodova vrijedi 1 € popusta na sljedeću narudžbu.",
"Earned points are pending until the pharmacy confirms it.":"Ostvareni bodovi su u obradi dok ljekarna ne potvrdi narudžbu.",
"Edit address":"Uredi adresu",
"Email about my orders":"E-mail o mojim narudžbama",
"Enter the email address on your account and we will send a link to set a new password. The link is valid for 24 hours.":"Upišite e-mail adresu svog računa i poslat ćemo vam link za postavljanje nove lozinke. Link vrijedi 24 sata.",
"Enter the email address you registered with.":"Upišite e-mail adresu s kojom ste se registrirali.",
"Enter your delivery address to see delivery options and prices.":"Upišite adresu za dostavu da vidite načine i cijene dostave.",
"Entered and confirmed here in the app":"Upisuje se i potvrđuje u aplikaciji",
"Every €1 spent earns 1 point. Prescription medicines and co-payments earn no points.":"Svaki potrošeni 1 € donosi 1 bod. Lijekovi na recept i participacije ne donose bodove.",
"Everyday essentials":"Za svaki dan",
"Everything from 21 pharmacies, ordered from here":"Sve iz 21 ljekarne, naručeno odavde",
"Face & body":"Lice i tijelo",
"Face & body care":"Njega lica i tijela",
"Face ID unlock":"Otključavanje Face ID-om",
"First aid":"Prva pomoć",
"First aid essentials":"Osnove prve pomoći",
"Food supplement. Not a substitute for a varied diet.":"Dodatak prehrani. Nije zamjena za raznovrsnu prehranu.",
"Food supplements are not a substitute for a varied diet. For medicines, ask your pharmacist.":"Dodaci prehrani nisu zamjena za raznovrsnu prehranu. Za lijekove pitajte svog magistra farmacije.",
"For mom and baby":"Za mame i bebe",
"For the whole family":"Za cijelu obitelj",
"Forgotten your password?":"Zaboravili ste lozinku?",
"GLS parcel locker":"GLS paketomat",
"GLS · collection code sent by SMS on arrival":"GLS · kod za preuzimanje dolazi SMS-om",
"Gentle routines for the evening":"Nježne rutine za večer",
"Get started":"Započnite",
"Getting ready for the cold months":"Priprema za hladne mjesece",
"Good day, Iva":"Dobar dan, Iva",
"Got it":"U redu",
"Hair & nails":"Kosa i nokti",
"Hair, skin and nails":"Kosa, koža i nokti",
"Hand over at the counter":"Pokažite na kasi",
"Hands off to the KEKS Pay app, then returns here":"Prebacuje u aplikaciju KEKS Pay, a zatim vraća ovdje",
"Hide password":"Sakrij lozinku",
"How WellPlus points work":"Kako funkcioniraju WellPlus bodovi",
"How would you like to receive it":"Kako želite primiti narudžbu",
"Hygiene and protection":"Higijena i zaštita",
"I accept the":"Prihvaćam",
"I confirm I have read the":"Potvrđujem da sam pročitao/la",
"I have read the":"Pročitao/la sam",
"If an account exists for":"Ako račun postoji za",
"If your question is about an order in progress, delivery continues as normal while we look into it.":"Ako se pitanje odnosi na narudžbu u obradi, dostava se nastavlja normalno dok provjeravamo.",
"Immunity essentials":"Osnove za imunitet",
"In stock today":"Danas na zalihi",
"In stock — ships within one working day.":"Na zalihi — otprema u jednom radnom danu.",
"In the app, turn on the WellPlus switch at the review step — it applies your whole balance, capped at the order total. In a pharmacy, tell the cashier you would like to use your points.":"U aplikaciji uključite WellPlus prekidač na koraku pregleda — koristi cijelo stanje, najviše do vrijednosti narudžbe. U ljekarni recite na kasi da želite iskoristiti bodove.",
"In the app: one switch at checkout — no amount to type in.":"U aplikaciji: jedan prekidač na naplati — bez upisivanja iznosa.",
"In-store purchases settle within a few hours. Until then the points show as processing in your activity list.":"Kupnje u ljekarni obrađuju se u roku od nekoliko sati. Do tada su bodovi u obradi na popisu aktivnosti.",
"Invoice downloaded":"Račun je preuzet",
"Invoices are kept for the statutory retention period.":"Računi se čuvaju u zakonom propisanom roku.",
"Just landed on the shelf":"Novo na polici",
"Keep browsing":"Nastavi pregledavati",
"Label / back of pack":"Etiketa / poleđina pakiranja",
"Leave the plastic card at home":"Plastičnu karticu ostavite kod kuće",
"Link sent again just now.":"Link je ponovno poslan.",
"Log in":"Prijava",
"Log in to see your WellPlus balance, your orders and your saved addresses.":"Prijavite se da vidite stanje WellPlus bodova, narudžbe i sačuvane adrese.",
"Looks good":"Sve u redu",
"Make default":"Postavi kao osnovnu",
"Member since 2024":"Član od 2024.",
"Min 20 characters":"Najmanje 20 znakova",
"Mom & baby":"Mama i beba",
"More to buy again":"Još za ponovnu kupnju",
"Most bought this week":"Najkupovanije ovaj tjedan",
"Mother & baby photo":"Fotografija mame i bebe",
"Multivitamins and immune support — the three asked for most at the counter.":"Multivitamini i podrška imunitetu — tri najtraženija na kasi.",
"My account":"Moj račun",
"My orders":"Moje narudžbe",
"Name on card":"Ime na kartici",
"New address":"Nova adresa",
"New arrivals":"Novo u ponudi",
"New in skincare":"Novo u njezi kože",
"New to e24?":"Prvi put na e24?",
"No card selected":"Nije odabrana kartica",
"No longer available":"Više nije dostupno",
"No points earned":"Bez ostvarenih bodova",
"No points yet — every €1 you spend earns 1 point.":"Još nema bodova — svaki potrošeni 1 € donosi 1 bod.",
"No results":"Nema rezultata",
"No. A purchase paid for using points does not earn new points.":"Ne. Kupnja plaćena bodovima ne donosi nove bodove.",
"No. Points never expire, and there is nothing to keep active.":"Ne. Bodovi ne istječu i ništa ne morate održavati aktivnim.",
"Not available with bank transfer. Switch to card or a wallet to redeem.":"Nije dostupno uz bankovnu uplatu. Za korištenje bodova odaberite karticu ili digitalni novčanik.",
"Nothing after a few minutes? Look in spam, or try again with another address.":"Ništa nakon nekoliko minuta? Provjerite spam ili pokušajte s drugom adresom.",
"Nothing in this category yet":"U ovoj kategoriji još nema proizvoda",
"Nothing matches that":"Ništa ne odgovara upitu",
"Notifications are delivered by the operating system. e24 cannot send them if push is switched off for the app in your phone settings.":"Obavijesti dostavlja operativni sustav. e24 ih ne može poslati ako su push obavijesti isključene za aplikaciju u postavkama telefona.",
"Offers and WellPlus news":"Akcije i WellPlus novosti",
"Omega & fish oil":"Omega i riblje ulje",
"On offer":"Na akciji",
"On the way":"U dostavi",
"One number":"Jedan broj",
"One point for every euro spent, in the app, on both webshops and at the register. 100 points are worth €1, from 100 points upward.":"Jedan bod za svaki potrošeni euro — u aplikaciji, na oba webshopa i na kasi. 100 bodova vrijedi 1 €, od 100 bodova nadalje.",
"One point for every euro,\nin every channel":"Jedan bod za svaki euro,\nu svakom kanalu",
"Only on offer":"Samo na akciji",
"Open 24 h":"Otvoreno 24 h",
"Open around the clock, every day":"Otvoreno 24 sata, svaki dan",
"Open source licences":"Licencije otvorenog koda",
"Open the app and your QR card without typing a password.":"Otvorite aplikaciju i svoju QR karticu bez upisivanja lozinke.",
"Open the link":"Otvorite link",
"Oral care":"Oralna higijena"
});
