/* Croatian dictionary, part 3: short labels + patterns with numbers. */
window.E24_HR = Object.assign(window.E24_HR || {}, {
"About":"O aplikaciji",
"Account":"Račun",
"Add":"Dodaj",
"Added":"Dodano",
"Adding":"Dodajemo",
"Address":"Adresa",
"Addresses":"Adrese",
"All":"Sve",
"Any":"Sve",
"App":"Aplikacija",
"Apply":"Primijeni",
"Availability":"Dostupnost",
"Cancel":"Odustani",
"Capsules":"Kapsule",
"Card":"Kartica",
"Cart":"Košarica",
"Category":"Kategorija",
"Change":"Promijeni",
"Clear":"Očisti",
"Close":"Zatvori",
"Company":"Podaci o firmi",
"Consents":"Privole",
"Copy":"Kopiraj",
"Current":"Trenutna",
"Default":"Osnovna",
"Delivered":"Dostavljeno",
"Delivery":"Dostava",
"Devices":"Uređaji",
"Done":"Gotovo",
"Earned":"Ostvareno",
"Edit":"Uredi",
"Enter":"Upiši",
"Expires":"Vrijedi do",
"FAQ":"Česta pitanja",
"Filter":"Filtriraj",
"Form":"Oblik",
"Free":"Besplatno",
"Group":"Skupina",
"Home":"Početna",
"Image":"Fotografija",
"Item":"Proizvod",
"Items":"Proizvodi",
"Label":"Naziv",
"Language":"Jezik",
"Later":"Kasnije",
"Legal":"Pravno",
"Liquid":"Tekućina",
"Membership":"Članstvo",
"Minerals":"Minerali",
"Never":"Nikada",
"Newest":"Najnovije",
"Notifications":"Obavijesti",
"Order":"Narudžba",
"Orders":"Narudžbe",
"Other":"Ostalo",
"Paid":"Plaćeno",
"Password":"Lozinka",
"Payment":"Plaćanje",
"Pharmacies":"Ljekarne",
"Phone":"Telefon",
"Points":"Bodovi",
"Postcode":"Poštanski broj",
"Preferences":"Postavke",
"Price":"Cijena",
"Probiotics":"Probiotici",
"Profile":"Profil",
"Refunded":"Vraćeno",
"Relevance":"Relevantnost",
"Remove":"Ukloni",
"Reset":"Poništi",
"Results":"Rezultati",
"Review":"Pregled",
"Searching":"Traženje",
"Sending":"Slanje",
"Shop":"Trgovina",
"Skin":"Koža",
"Skip":"Preskoči",
"Softgels":"Kapsule",
"Spent":"Potrošeno",
"Store":"Ljekarna",
"Sub-category":"Podkategorija",
"Support":"Podrška",
"Tablets":"Tablete",
"Total":"Ukupno",
"Vitamins":"Vitamini",
"Work":"Posao",
"Search":"Traži",
"Search products":"Traži proizvode",
"Filters":"Filtri",
"Continue":"Nastavi",
"Back":"Natrag",
"Save":"Sačuvaj",
"Email":"E-mail",
"Name":"Ime i prezime",
"City":"Grad",
"Note for the courier":"Napomena za dostavljača",
"Confirm":"Potvrdi",
"Subject":"Tema",
"Message":"Poruka",
"Sent":"Poslano",
"Pending":"U obradi",
"Processing":"U obradi",
"In progress":"U obradi",
"Ready":"Spremno",
"Ready for pick-up":"Spremno za preuzimanje",
"Balance":"Stanje",
"Rewards":"Pogodnosti",
"Settings":"Postavke",
"Sign in":"Prijava",
"Quantity":"Količina",
"Subtotal":"Iznos",
"Discount":"Popust",
"Shipping":"Dostava"
});

/* Patterns: copy with numbers or names substituted in. */
window.E24_HR_RULES = [
  [/^You have ([\d.,]+) points ready to spend\.$/, "Imate $1 bodova za potrošiti."],
  [/^You have ([\d.,]+) points\.?$/, "Imate $1 bodova."],
  [/^([\d.,]+) points$/, "$1 bodova"],
  [/^([\d.,]+) points now$/, "$1 bodova sada"],
  [/^\+([\d.,]+) points$/, "+$1 bodova"],
  [/^\+([\d.,]+) pts$/, "+$1 bodova"],
  [/^([\d.,]+) pts$/, "$1 bodova"],
  [/^([\d.,]+) points used$/, "iskorišteno $1 bodova"],
  [/^([\d.,]+) points on the way$/, "$1 bodova je na putu"],
  [/^Pending · ([\d.,]+) pts$/, "U obradi · $1 bodova"],
  [/^(\d+) products?$/, "$1 proizvoda"],
  [/^(\d+) items?$/, "$1 komada"],
  [/^(\d+) results?$/, "$1 rezultata"],
  [/^(\d+) in your cart$/, "$1 u košarici"],
  [/^(\d+) products? · ([\d.,]+) points$/, "$1 proizvoda · $2 bodova"],
  [/^Order (WP-[\d-]+)$/, "Narudžba $1"],
  [/^Order (WP-[\d-]+) is on the way$/, "Narudžba $1 je u dostavi"],
  [/^([\d.,]+) points to your first redemption \(100 minimum\)\.$/, "$1 bodova do prvog iskorištavanja (najmanje 100)."],
  [/^([\d.,]+) points so far\. Redemption starts at 100 points — ([\d.,]+) to go\.$/, "Do sada $1 bodova. Iskorištavanje počinje od 100 bodova — još $2."],
  [/^(\d+) of (\d+)$/, "$1 od $2"],
  [/^Step (\d+) of (\d+)$/, "Korak $1 od $2"],
  [/^([\d.,]+) products in this category$/, "$1 proizvoda u ovoj kategoriji"],
  [/^We'll credit (\d+) points once your transfer arrives and the order is closed\.$/, "Dodat ćemo $1 bodova kada uplata dođe i narudžba se zaključi."],
  [/^Points are worth €([\d,]+) here\.$/, "Bodovi ovdje vrijede $1 €."],
  [/^(\d+) points on this order$/, "$1 bodova na ovu narudžbu"],
  [/^You have ([\d.,]+) points \(€([\d,]+)\) available to spend at review\.$/, "Imate $1 bodova (€$2) za iskoristiti na pregledu."],
  [/^([\d.,]+) points \(€([\d,]+)\)$/, "$1 bodova (€$2)"],
  [/^€([\d,]+) off$/, "€$1 popusta"],
  [/^(\d+) tablets?$/, "$1 tableta"],
  [/^(\d+) capsules?$/, "$1 kapsula"],
  [/^−([\d.,]+) pts$/, "−$1 bodova"],
  [/^(\d+) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{4})$/, "$1. $2 $3."],
  [/^Purchase · (.+)$/, "Kupnja · $1"],
  [/^Earns (\d+) WellPlus points?$/, "Donosi $1 WellPlus bodova"],
  [/^Earns (\d+) points?$/, "Donosi $1 bodova"],
  [/^([\d.,]+) points → €([\d,]+) off$/, "$1 bodova → $2 € popusta"],
  [/^Items \((\d+)\)$/, "Proizvodi ($1)"],
  [/^Card · (.+)$/, "Kartica · $1"],
  [/^Cash on delivery · (.+)$/, "Plaćanje pri dostavi · $1"],
  [/^Total \((\d+) items?\)$/, "Ukupno ($1 komada)"],
  [/^Prices are for (.+)\.$/, "Cijene su za $1."],
  [/^Delivery to (.+)$/, "Dostava na $1"],
  [/^Ready (.+)$/, "Spremno $1"],
  [/^Expires (.+)$/, "Vrijedi do $1"],
  [/^Items \((\d+)\) · (.+)$/, "Proizvodi ($1) · $2"],
  [/^You save €([\d,]+)$/, "Ušteda $1 €"],
  [/^Order (.+) placed$/, "Narudžba $1 je poslana"],
  [/^You'll earn (\d+) points?$/, "Ostvarit ćete $1 bodova"],
  [/^You’ll earn (\d+) points?$/, "Ostvarit ćete $1 bodova"],
  [/^Time left to confirm: (.+)$/, "Vrijeme za potvrdu: $1"],
  [/^Confirming your payment with (.+)$/, "Potvrđujemo vaše plaćanje s $1"],
  [/^\+(\d+) points on the way$/, "+$1 bodova je na putu"]
];
