/* Croatian dictionary, part 4: the remainder. */
window.E24_HR = Object.assign(window.E24_HR || {}, {
"Points notifications are on":"Obavijesti o bodovima su uključene",
"Points notifications are off":"Obavijesti o bodovima su isključene",
"Offers and news notifications are on":"Obavijesti o ponudama i novostima su uključene",
"Offers and news notifications are off":"Obavijesti o ponudama i novostima su isključene",
"Account and security notifications are on":"Obavijesti o računu i sigurnosti su uključene",
"Account and security notifications are off":"Obavijesti o računu i sigurnosti su isključene",
"Order notifications are on":"Obavijesti o narudžbama su uključene",
"Order notifications are off":"Obavijesti o narudžbama su isključene",
"Order emails are on":"E-mailovi o narudžbama su uključeni",
"Order emails are off — emails for orders in progress still arrive":"E-mailovi o narudžbama su isključeni — e-mailovi za narudžbe u tijeku i dalje dolaze",
"SMS notifications are on":"SMS obavijesti su uključene",
"SMS notifications are off":"SMS obavijesti su isključene",
"Personalised offers are on":"Personalizirane ponude su uključene",
"Personalised offers are off":"Personalizirane ponude su isključene",
"Date":"Datum",
"Where":"Gdje",
"Value":"Vrijednost",
"Earned at 1 point for every €1 spent.":"Zaračunato po 1 bod za svaki potrošeni 1 €.",
"A refund removes the points the purchase earned.":"Povrat uklanja bodove koje je kupnja donijela.",
"Redeemed at 100 points = €1.":"Iskorišteno po 100 bodova = 1 €.",
"This movement is still settling. In-store purchases can take a few hours to appear in your balance.":"Ova promjena još se obračunava. Kupnje u ljekarni mogu se pojaviti u stanju nakon nekoliko sati.",
"How points work":"Kako bodovi funkcioniraju",
", a reset link is on its way. It expires in 24 hours.":", link za promjenu lozinke je na putu. Vrijedi 24 sata.",
". Open it and your account is complete.":". Otvorite ga i vaš račun je dovršen.",
"Every purchase at Ljekarne Švaljek turns into a discount you can use whenever you like.":"Svaka kupnja u Ljekarnama Švaljek postaje popust koji možete iskoristiti kada želite.",
"Ljekarna Švaljek — Ilica 191. Balance 1.273 points.":"Ljekarna Švaljek — Ilica 191. Stanje 1.273 boda.",
"WellPlus is on hold until you open the link we sent to ana.horvat@primjer.hr. Shopping works normally.":"WellPlus je na čekanju dok ne otvorite link koji smo poslali na ana.horvat@primjer.hr. Kupovina radi normalno.",
"by Ljekarne Švaljek":"Ljekarne Švaljek",
"e24 by Ljekarne Švaljek · 21 pharmacies · Version 1.0":"e24 by Ljekarne Švaljek · 21 ljekarna · Verzija 1.0",
"Security & sign-in":"Sigurnost i prijava",
"Iron":"Željezo",
"Seat":"Sjedalo",
"now":"sada",
"optional":"neobavezno",
"required":"obavezno",
"points · ≈ €12,47":"bodova · ≈ 12,47 €",
"≈ €12,47 to spend":"≈ 12,47 € za potrošiti",
"Reference SUP-20831-118":"Poziv na broj SUP-20831-118",
"M-01 — skeleton while a list loads":"M-01 — skeleton dok se popis učitava",
"M-02 — one toast pattern":"M-02 — jedan obrazac obavijesti",
"M-03 — a list that failed to load":"M-03 — popis koji se nije učitao",
"M-03 — inline validation":"M-03 — provjera u obrascu",
"S1 — no connection":"S1 — nema veze",
"S2 — service unavailable":"S2 — usluga nedostupna",
"E4 — notification settings":"E4 — postavke obavijesti",
"E4 — push denied at OS level":"E4 — push odbijen na razini sustava",
"D1 — first generation":"D1 — prvo generiranje",
"D1 — offline but usable":"D1 — bez veze, ali upotrebljivo",
"D1 — till redemption still settling":"D1 — iskorištavanje na kasi još u obradi",
"Checkout":"Naplata",
"Cart":"Košarica",
"Add to order":"Dodaj u narudžbu",
"SUBTOTAL":"IZNOS",
"Subtotal":"Iznos",
"points on this order":"bodova na ovu narudžbu",
"points (":"bodova (",
") available to spend at review.":") za iskoristiti na pregledu.",
"points ready to spend.":"bodova za potrošiti.",
"You have":"Imate",
"points to your first redemption (100 minimum).":"bodova do prvog iskorištavanja (najmanje 100).",
"points used":"bodova iskorišteno",
"points on the way":"bodova je na putu",
"points now":"bodova sada",
"pts":"bodova",
"points":"bodova",
"product":"proizvod",
"products":"proizvoda",
"items":"komada",
"item":"komad",
"in your cart":"u košarici",
"Checkout":"Naplata",
"LAST 30 DAYS":"POSLJEDNJIH 30 DANA",
"Purchase · Ljekarna Švaljek, Zagreb":"Kupnja · Ljekarna Švaljek, Zagreb",
"Purchase · Centar zdravih rješenja":"Kupnja · Centar zdravih rješenja",
"Store":"Ljekarna",
"App":"Aplikacija",
"processing":"u obradi",
"100 points = €1, redeemable from 100 points upward.":"100 bodova = 1 €, iskoristivo od 100 bodova nadalje.",
"In store: just tell the cashier you'd like to use your points.":"U ljekarni: samo recite na kasi da želite iskoristiti bodove.",
"Points never expire — spend them at checkout or at the register.":"Bodovi ne istječu — iskoristite ih na naplati ili na kasi.",
"21 Aug 2026":"21. 8. 2026.",
"18 Aug 2026":"18. 8. 2026.",
"12 Aug 2026":"12. 8. 2026.",
"4 Aug 2026":"4. 8. 2026.",
"29 Jul 2026":"29. 7. 2026.",
"19 Aug 2026":"19. 8. 2026.",
"12 Aug":"12. 8.",
"4 Aug":"4. 8.",
"19 Jul":"19. 7.",
"MIN":"MIN",
"Last 30 days":"Posljednjih 30 dana",
"· Store":"· Ljekarna",
"· App":"· Aplikacija",
"Ljekarna Švaljek, Zagreb":"Ljekarna Švaljek, Zagreb",
"Vitamins\n& minerals":"Vitamini\ni minerali",
"Face &\nbody care":"Njega lica\ni tijela",
"Mom\n& baby":"Mama\ni beba",
"Mom &\nbaby":"Mama\ni beba",
"First aid\nessentials":"Osnove\nprve pomoći",
"Oral care":"Oralna higijena",
"My card":"Moja kartica",
"Membership number":"Broj članstva",
"Show code":"Prikaži kod",
"Full screen":"Cijeli ekran",
"Product":"Proizvod",
"Continue to delivery":"Nastavi na dostavu",
"Review order":"Pregledaj narudžbu",
"Card details are handled by the bank. You confirm with 3-D Secure without leaving the app.":"Podatke o kartici obrađuje banka. Potvrđujete 3-D Secureom bez izlaska iz aplikacije.",
"Entered and confirmed here in the app":"Upisuje se i potvrđuje u aplikaciji",
"Card · Entered and confirmed here in the app":"Kartica · upisuje se i potvrđuje u aplikaciji",
"Google Pay":"Google Pay",
"Bank transfer · Pay by IBAN in your banking app":"Bankovna uplata · plaćanje po IBAN-u u aplikaciji banke",
"KEKS Pay · Hands off to the KEKS Pay app, then returns here":"KEKS Pay · prebacuje u aplikaciju KEKS Pay, a zatim vraća ovdje",
"Aircash · 4-minute window to confirm in the Aircash app":"Aircash · 4 minute za potvrdu u aplikaciji Aircash",
"Delivery":"Dostava",
"Address":"Adresa",
"Items (":"Proizvodi (",
"Prices are for":"Cijene su za",
"Total (":"Ukupno (",
"Delivery (":"Dostava (",
"points on the way":"bodova je na putu",
"on the way":"je na putu",
"Order":"Narudžba",
"Order placed":"Narudžba je poslana",
"Track this order":"Prati ovu narudžbu",
"Back to home":"Natrag na početnu",
"Bank authentication":"Autentifikacija banke",
"This screen is your bank’s, shown inside the app. e24 never sees the code.":"Ovaj ekran pripada vašoj banci i prikazan je unutar aplikacije. e24 nikada ne vidi kod.",
"This screen is your bank's, shown inside the app. e24 never sees the code.":"Ovaj ekran pripada vašoj banci i prikazan je unutar aplikacije. e24 nikada ne vidi kod.",
"Enter the code from your banking app":"Upišite kod iz aplikacije banke",
"Confirm payment":"Potvrdi plaćanje",
"Waiting for confirmation":"Čekamo potvrdu",
"Payment confirmed":"Plaćanje je potvrđeno",
"Order reserved":"Narudžba je rezervirana",
"Continue in":"Nastavi u",
"points on the way":"bodova je na putu",
"We'll email a confirmation and let you know when it's on the way.":"Poslat ćemo potvrdu e-mailom i javiti kada narudžba bude u dostavi.",
"We’ll email a confirmation and let you know when it’s on the way.":"Poslat ćemo potvrdu e-mailom i javiti kada narudžba bude u dostavi.",
"It goes to the pharmacy as soon as your transfer arrives.":"Ide u ljekarnu čim vaša uplata dođe."
});
