/* Croatian dictionary, part 2 of 2. Keys are the English source strings. */
window.E24_HR = Object.assign(window.E24_HR || {}, {
"Order WP-20826-441 is on the way":"Narudžba WP-20826-441 je u dostavi",
"Order confirmed, sent, ready, refunded. Cannot be turned off while an order is in progress.":"Narudžba potvrđena, poslana, spremna, vraćena. Ne može se isključiti dok je narudžba u obradi.",
"Order numbers look like WP-20826-441.":"Brojevi narudžbi izgledaju kao WP-20826-441.",
"Order online, pick up nearby.":"Naručite online, preuzmite u blizini.",
"Order placed":"Narudžba je poslana",
"Order reserved":"Narudžba je rezervirana",
"Orders & details":"Narudžbe i podaci",
"Orders already downloaded stay visible. Only the refresh failed.":"Već preuzete narudžbe ostaju vidljive. Nije uspjelo samo osvježavanje.",
"Orders and payments":"Narudžbe i plaćanja",
"Orders placed in a pharmacy or on eljekarna24.hr are not listed here, but their points are.":"Kupnje u ljekarni ili na eljekarna24.hr nisu na ovom popisu, ali njihovi bodovi jesu.",
"Over €20":"Više od 20 €",
"Overseas Express · tracking 4109 8823 71":"Overseas Express · praćenje 4109 8823 71",
"Parcel locker":"Paketomat",
"Password updated. You stay signed in on this device; other devices will ask for the new password.":"Lozinka je promijenjena. Na ovom uređaju ostajete prijavljeni; ostali uređaji zatražit će novu lozinku.",
"Pay by IBAN in your banking app":"Plaćanje po IBAN-u u aplikaciji banke",
"Payment confirmed":"Plaćanje je potvrđeno",
"Payment method":"Način plaćanja",
"Payment methods":"Načini plaćanja",
"Pending until the pharmacy confirms the order — usually a few hours.":"U obradi dok ljekarna ne potvrdi narudžbu — obično nekoliko sati.",
"Personal details":"Osobni podaci",
"Personalised offers":"Personalizirane ponude",
"Pharmacist advice on dosing through winter, plus 20% off Supradyn Kids Imuno Boost.":"Savjeti magistra farmacije o doziranju kroz zimu i 20% popusta na Supradyn Kids Imuno Boost.",
"Pharmacist picks for cold season":"Odabir magistara za sezonu prehlada",
"Pharmacy counter photo":"Fotografija ljekarničke kase",
"Pick what your message is about.":"Odaberite na što se poruka odnosi.",
"Pickup shop":"Mjesto preuzimanja",
"Place order":"Pošalji narudžbu",
"Points and redemptions":"Bodovi i iskorištavanje",
"Points earned in a pharmacy or on a webshop, and points spent. The only channel that reports them.":"Bodovi ostvareni u ljekarni ili na webshopu i potrošeni bodovi. Jedini kanal koji ih javlja.",
"Points earned on this order were removed when the refund was processed.":"Bodovi ostvareni na ovoj narudžbi uklonjeni su pri obradi povrata.",
"Points earned per €1":"Bodovi po 1 €",
"Points expiry":"Istek bodova",
"Points for this order are pending until the transfer clears.":"Bodovi za ovu narudžbu su u obradi do evidentiranja uplate.",
"Points from in-store purchases settle within a few hours. Refunds remove the points the purchase earned.":"Bodovi iz ljekarne obrađuju se u roku od nekoliko sati. Povrat uklanja bodove ostvarene tom kupnjom.",
"Points from this order appear once the pharmacy confirms it.":"Bodovi s ove narudžbe prikazuju se kada ju ljekarna potvrdi.",
"Points never expire.":"Bodovi ne istječu.",
"Points never expire. 100 points = €1.":"Bodovi ne istječu. 100 bodova = 1 €.",
"Points once the order is closed":"Bodovi nakon zaključenja narudžbe",
"Points were used on this order, so it earns no new points.":"Na ovoj narudžbi iskorišteni su bodovi, pa ne donosi nove bodove.",
"Points worth more than the order":"Bodovi vrijede više od narudžbe",
"Preferred parcel locker":"Preferirani paketomat",
"Pregnancy and nursing":"Trudnoća i dojenje",
"Prenatal & folate":"Trudnoća i folati",
"Prescription medicines and co-payments are settled in the pharmacy and cannot be paid for in the app.":"Lijekovi na recept i participacije plaćaju se u ljekarni i ne mogu se platiti u aplikaciji.",
"Preselected at every checkout. You can still change it per order.":"Unaprijed odabrano na svakoj naplati. Možete promijeniti za pojedinu narudžbu.",
"Price: high to low":"Cijena: od najviše",
"Price: low to high":"Cijena: od najniže",
"Privacy policy":"Izjava o privatnosti",
"Product suggestions based on what you have bought. Never medical advice.":"Predlošci proizvoda na temelju vaših kupnji. Nikada medicinski savjet.",
"Profile, addresses and saved cards are deleted.":"Profil, adrese i sačuvane kartice se brišu.",
"Purchase · e24 app":"Kupnja · e24 aplikacija",
"Purchase · eljekarna24.hr":"Kupnja · eljekarna24.hr",
"Push is the only place points and order updates are announced. Choose what you want to hear about.":"Push obavijesti su jedino mjesto gdje javljamo bodove i status narudžbe. Odaberite o čemu želite biti obaviješteni.",
"Read the FAQ":"Pročitajte česta pitanja",
"Ready today after 16:00":"Spremno danas nakon 16:00",
"Ready today after 18:00":"Spremno danas nakon 18:00",
"Ready tomorrow morning":"Spremno sutra ujutro",
"Recent activity":"Nedavne aktivnosti",
"Recent additions for skin, hair and nails — all in stock.":"Novi proizvodi za kožu, kosu i nokte — svi na zalihi.",
"Recent searches":"Nedavne pretrage",
"Redeemed at checkout":"Iskorišteno na naplati",
"Redemption removed on the way back":"Iskorištavanje bodova je uklonjeno",
"Refreshing your balance…":"Osvježavamo stanje…",
"Refund · returned item":"Povrat · vraćeni proizvod",
"Registered name":"Ime na računu",
"Reset your password":"Postavite novu lozinku",
"SMS notifications":"SMS obavijesti",
"Save address":"Sačuvaj adresu",
"Save and log in":"Sačuvaj i prijavi se",
"Save changes":"Sačuvaj promjene",
"Save password":"Sačuvaj lozinku",
"Save this card":"Sačuvaj ovu karticu",
"Screen brightness is raised while the code is open.":"Svjetlina ekrana povećava se dok je kod otvoren.",
"Secure page from the payment provider, shown inside e24. You can cancel at any time.":"Sigurna stranica pružatelja plaćanja, prikazana unutar e24. Možete odustati u svakom trenutku.",
"Security & sign-in":"Sigurnost i prijava",
"See immunity picks":"Vidi odabir za imunitet",
"See new arrivals":"Vidi novo u ponudi",
"See the selection":"Vidi odabir",
"Send a message":"Pošaljite poruku",
"Send a new code":"Pošalji novi kod",
"Send me pharmacist advice and WellPlus news, by email and push. You can turn this off at any time in":"Želim savjete magistara farmacije i WellPlus novosti, e-mailom i push obavijestima. Možete isključiti u svakom trenutku u",
"Send message":"Pošalji poruku",
"Send the link":"Pošalji link",
"Send the link again":"Pošalji link ponovno",
"Set a new password":"Postavi novu lozinku",
"Show all products":"Prikaži sve proizvode",
"Show my card":"Prikaži moju karticu",
"Show password":"Prikaži lozinku",
"Show the QR code at the till and your points are added on the spot. The same balance, the same discount, no card to carry.":"Pokažite QR kod na kasi i bodovi se dodaju na mjestu. Isto stanje, isti popust, bez kartice u novčaniku.",
"Show this code at the register in any of the 21 pharmacies. Points are added to your balance within a few hours.":"Pokažite ovaj kod na kasi u bilo kojoj od 21 ljekarne. Bodovi se dodaju na stanje u roku od nekoliko sati.",
"Show your WellPlus QR at the register to use points instead.":"Za korištenje bodova pokažite WellPlus QR na kasi.",
"Sign out":"Odjava",
"Sign out of e24?":"Odjaviti se s e24?",
"Sign-in on a new device, password changes, service notices.":"Prijava na novom uređaju, promjene lozinke, servisne obavijesti.",
"Signing in":"Prijava",
"Signing out a device does not affect your points or your orders. Your WellPlus card keeps working in the pharmacy.":"Odjava uređaja ne utječe na bodove ni narudžbe. Vaša WellPlus kartica i dalje radi u ljekarni.",
"Skin, hair and nails":"Koža, kosa i nokti",
"Skincare photo":"Fotografija njege kože",
"Skip for now":"Preskoči za sada",
"Something else":"Nešto drugo",
"Something wrong with this order?":"Nešto nije u redu s narudžbom?",
"Sort by":"Sortiraj",
"Start shopping":"Počni kupovinu",
"Stay signed in":"Ostani prijavljen",
"Still stuck? Contact us":"Još ne ide? Kontaktirajte nas",
"Stored by the bank for your next order.":"Banka je čuva za vašu sljedeću narudžbu.",
"Street and number":"Ulica i broj",
"Sun care":"Zaštita od sunca",
"Supplement shelf photo":"Fotografija police s dodacima",
"Support cannot give medical advice or change a prescription. For questions about a medicine, speak to a pharmacist in any of the 21 pharmacies.":"Podrška ne može dati medicinski savjet ni promijeniti recept. Za pitanja o lijeku obratite se magistru farmacije u bilo kojoj od 21 ljekarne.",
"Surface disinfection and gloves for the home medicine cabinet.":"Dezinfekcija površina i rukavice za kućnu ljekarnu.",
"Terms of use":"Uvjeti korištenja",
"Terms, coupon and edit links":"Uvjeti, kupon i linkovi za uređivanje",
"That does not look like an email address. Check for a typo.":"Ovo ne izgleda kao e-mail adresa. Provjerite ima li greške.",
"The QR card replaces the plastic one at the register.":"QR kartica na kasi zamjenjuje plastičnu.",
"The QR code works once you open the confirmation link we sent. Until then, points cannot be added at the register.":"QR kod radi kada otvorite link za potvrdu koji smo poslali. Do tada se bodovi ne mogu dodati na kasi.",
"The app":"Aplikacija",
"The app follows this setting everywhere, including order statuses.":"Aplikacija slijedi ovu postavku svugdje, uključujući statuse narudžbi.",
"The cashier's discount is applied. Your balance here updates as soon as the pharmacy's till reports it.":"Popust na kasi je primijenjen. Stanje ovdje ažurira se kada ga ljekarnička kasa javi.",
"The code below works at the till. The balance is the last value this phone received.":"Kod ispod radi na kasi. Stanje je posljednja vrijednost koju je telefon primio.",
"The demo catalogue carries a few products only. Tap All to see everything.":"Demo katalog sadrži samo nekoliko proizvoda. Dodirnite Sve za cijelu ponudu.",
"The home first aid shelf":"Kućna polica prve pomoći",
"The mineral shelf":"Polica s mineralima",
"The name on this address becomes the name on your WellPlus card.":"Ime s ove adrese postaje ime na vašoj WellPlus kartici.",
"The name on your default address is the name printed on your WellPlus card.":"Ime s vaše osnovne adrese ispisuje se na WellPlus kartici.",
"The number is sent straight to the bank over an encrypted connection.":"Broj se šalje izravno banci šifriranom vezom.",
"The order waits 5 days at the counter.":"Narudžba čeka 5 dana na mjestu preuzimanja.",
"The pharmacy, in your pocket":"Ljekarna u vašem džepu",
"The three best-reviewed supplements for skin, hair and nails.":"Tri najbolje ocijenjena dodatka za kožu, kosu i nokte.",
"The three our pharmacists reach for first when the cold months start.":"Tri koja naši magistri prvi preporuče kad počnu hladni mjeseci.",
"The two passwords do not match.":"Lozinke se ne podudaraju.",
"The two products you picked before creating the account are still here.":"Dva proizvoda odabrana prije kreiranja računa su još ovdje.",
"These products did not load.":"Ovi proizvodi se nisu učitali.",
"Thursday 3 September":"Četvrtak, 3. rujna",
"To pay":"Za plaćanje",
"Top rated in beauty":"Najbolje ocijenjeno u njezi",
"Track this order":"Prati ovu narudžbu",
"Transfer the amount to complete the order":"Uplatite iznos za dovršetak narudžbe",
"Transfer these details":"Podaci za uplatu",
"Trending in the pharmacy":"Popularno u ljekarni",
"Try a shorter search, or browse a category.":"Pokušajte s kraćim upitom ili pregledajte kategoriju.",
"Try a shorter word, or start from one of these.":"Pokušajte s kraćom riječju ili počnite od jedne od ovih.",
"Try again":"Pokušaj ponovno",
"Two additions this month, in stock in 21 pharmacies.":"Dva nova proizvoda ovaj mjesec, na zalihi u 21 ljekarni.",
"Two shelves customers restock through the winter months.":"Dvije police koje kupci obnavljaju kroz zimske mjesece.",
"Two-step verification":"Dvostruka provjera",
"Under €10":"Do 10 €",
"Updated at 07:52, before the connection dropped.":"Ažurirano u 07:52, prije prekida veze.",
"Use another address":"Koristi drugu adresu",
"Use as my default address":"Postavi kao osnovnu adresu",
"Use my points":"Iskoristi moje bodove",
"Use the IBAN above with the reference from each order — never without it.":"Koristite IBAN iznad s pozivom na broj iz svake narudžbe — nikada bez njega.",
"Use these details in your banking app. Quote the reference exactly — it is how the payment is matched to your order.":"Upišite ove podatke u aplikaciju banke. Poziv na broj prepišite točno — po njemu se uplata povezuje s narudžbom.",
"Use this locker":"Odaberi ovaj paketomat",
"Use this pharmacy":"Odaberi ovu ljekarnu",
"Value of 100 points":"Vrijednost 100 bodova",
"Version 1.0 (build 104)":"Verzija 1.0 (build 104)",
"View rewards":"Vidi pogodnosti",
"Vitamin C, D3 and selenium — the three most asked for at the counter.":"Vitamin C, D3 i selen — tri najtraženija na kasi.",
"Vitamin D season":"Sezona vitamina D",
"Vitamins & minerals":"Vitamini i minerali",
"Vitamins for children and multivitamins — what pharmacists recommend most often.":"Vitamini za djecu i multivitamini — ono što magistri najčešće preporuče.",
"We need an email address to answer you.":"Potrebna nam je e-mail adresa da vam odgovorimo.",
"We notify you as soon as the order is ready to collect.":"Javljamo vam čim narudžba bude spremna za preuzimanje.",
"We reply within one working day, to iva.jurasin@primjer.hr.":"Odgovaramo u roku od jednog radnog dana, na iva.jurasin@primjer.hr.",
"We sent a confirmation link to":"Poslali smo link za potvrdu na",
"We sent a six-digit code to +385 91 ••• 5678. It is filled in for you in this prototype — confirm to continue.":"Poslali smo šestocifreni kod na +385 91 ••• 5678. U ovom prototipu je već upisan — potvrdite za nastavak.",
"We will email a copy of your data to iva.jurasin@primjer.hr within 24 hours.":"Kopiju vaših podataka poslat ćemo na iva.jurasin@primjer.hr u roku od 24 sata.",
"Welcome back":"Dobro došli natrag",
"Welcome to WellPlus, Ana. Your balance starts at":"Dobro došli u WellPlus, Ana. Vaše stanje počinje s",
"WellPlus membership closes and unspent points are lost.":"Članstvo u WellPlusu se zatvara, a neiskorišteni bodovi se gube.",
"WellPlus points":"WellPlus bodovi",
"WellPlus points are added once the payment clears.":"WellPlus bodovi dodaju se nakon evidentiranja uplate.",
"WellPlus points are not a code — use the switch above.":"WellPlus bodovi nisu kod — koristite prekidač iznad.",
"WellPlus stays on hold until the address is confirmed — no points, no QR card.":"WellPlus je na čekanju do potvrde adrese — bez bodova i bez QR kartice.",
"What our customers rate highest":"Što naši kupci najbolje ocjenjuju",
"Withdrawing a consent takes effect immediately. It does not affect your WellPlus membership or your points.":"Povlačenje privole stupa na snagu odmah. Ne utječe na članstvo u WellPlusu ni na bodove.",
"Works offline — the code is stored on this device.":"Radi bez interneta — kod je sačuvan na ovom uređaju.",
"Worth €12,47 at checkout or at the till.":"Vrijedi 12,47 € na naplati ili na kasi.",
"Write your message before sending.":"Napišite poruku prije slanja.",
"Yes, delete my account":"Da, zatvori moj račun",
"You are redirected to":"Preusmjeravamo vas na",
"You can browse and order in the meantime.":"U međuvremenu možete pregledavati i naručivati.",
"You can close the app — the order completes on its own and you will get an email either way.":"Možete zatvoriti aplikaciju — narudžba se dovršava sama i u svakom slučaju dobivate e-mail.",
"You have":"Imate",
"Your WellPlus card is in your wallet. The QR stays valid even if your balance changes.":"Vaša WellPlus kartica je u Walletu. QR ostaje važeći i kada se stanje promijeni.",
"Your WellPlus membership starts with the account — points from the register are added to the same balance.":"Članstvo u WellPlusu počinje s računom — bodovi s kase dodaju se na isto stanje.",
"Your account is ready":"Vaš račun je spreman",
"Your card":"Vaša kartica",
"Your cards":"Vaše kartice",
"Your cart is empty.":"Vaša košarica je prazna.",
"Your details are saved.":"Vaši podaci su sačuvani.",
"Your message is with support":"Vaša poruka je kod podrške",
"Your name appears here after your first delivery address":"Vaše ime prikazat će se nakon prve adrese za dostavu",
"Your name comes from your first delivery address. The card works normally without it.":"Vaše ime dolazi s prve adrese za dostavu. Kartica radi normalno i bez njega.",
"Your points and orders stay on your account. You will need your email and password to sign back in.":"Bodovi i narudžbe ostaju na vašem računu. Za ponovnu prijavu trebate e-mail i lozinku.",
"Zagreb · active now":"Zagreb · trenutno aktivno",
"Zagreb · last used 19 Aug 2026":"Zagreb · zadnje korištenje 19. 8. 2026.",
"and agree to my data being processed as described in it.":"i pristajem na obradu svojih podataka kako je tamo opisano.",
"and the WellPlus programme rules.":"i pravila WellPlus programa.",
"and wish to continue with the order.":"i želim nastaviti s narudžbom.",
"notification settings":"postavkama obavijesti",
"pharmacies · webshop":"ljekarne · webshop",
"points now":"bodova sada",
"privacy policy":"izjavu o privatnosti",
"terms of use":"uvjete korištenja",
"the app":"aplikacija",
"the provider":"pružatelj usluge",
"welcome points":"bodova dobrodošlice",
"Below the threshold — visible, inactive":"Ispod granice — vidljivo, neaktivno",
"Cart survived registration":"Košarica je sačuvana nakon registracije",
"Campaign push, sent only with marketing consent. Advice first, discount second.":"Kampanjska obavijest, samo uz privolu za marketing. Prvo savjet, onda popust.",
"Croatia's pharmacy points arrive by push only — there is no message inbox in the app. Turn notifications back on for e24 in your phone settings.":"Bodovi i obavijesti dolaze samo push obavijestima — u aplikaciji nema sandučića. Uključite obavijesti za e24 u postavkama telefona.",
"Detail or in-use photo":"Fotografija detalja ili u upotrebi",
"Guest PDP":"Stranica proizvoda za gosta",
"Guest shop":"Trgovina za gosta",
"Hyaluronic serum":"Hijaluronski serum",
"Baby lotion":"Losion za bebe",
"Sunscreen SPF 50":"Krema za sunčanje SPF 50",
"Omega 3":"Omega 3",
"Vitamin C":"Vitamin C",
"Vitamin D":"Vitamin D",
"Vitamin D3":"Vitamin D3",
"Imuno Boost":"Imuno Boost",
"Kids Imuno":"Kids Imuno",
"Push template — campaign":"Predložak obavijesti — kampanja",
"Push template — order":"Predložak obavijesti — narudžba",
"Push template — points":"Predložak obavijesti — bodovi",
"Chrome on Windows":"Chrome na Windowsu",
"Change location":"Promijeni lokaciju",
"1 km":"1 km",
"Pending ·":"U obradi ·",
"+26 points":"+26 bodova",
"+24 points on this order, added once the pharmacy confirms it.":"+24 boda na ovu narudžbu, dodaju se kada ljekarna potvrdi.",
"+41 pts from a recent purchase is still processing and will appear in your balance shortly. In-store purchases can take a few hours to settle.":"+41 bod s nedavne kupnje još je u obradi i uskoro će se prikazati na stanju. Kupnje u ljekarni mogu se obraditi u roku od nekoliko sati."
});
